[package]
name = "shrs_sound"
author = "Nithin Muthukumar"
about = "Sound plugin for shrs"
version = "0.1.0"
edition = "2021"
description = "Sound plugin for shrs"


[dependencies]
shrs = { git = "https://github.com/MrPicklePinosaur/shrs" }
dirs = "5"
rodio = "0.17.3"
