[package]
name = "shrs_sound"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shrs = { git = "https://github.com/MrPicklePinosaur/shrs" }
dirs = "5"
rodio = "0.17.3"
